<?php

namespace FlickrBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Get one or null categories
     * 
     * @param int $id
     * @return type
     */
    public function getCategory($id)
    {
        $qb = $this->createQueryBuilder('category')
            ->where('category.id = :id AND category.deleted = 0')
            ->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }    
    
    /**
     * Get all categories
     * 
     * @param bool $justQuery
     * @return type
     */
    public function getCategories()
    {
        $qb = $this->createQueryBuilder('category')
            ->where('category.deleted = 0');
        
        return $qb->getQuery();
    } 
    
    /**
     * Get all categories data
     * 
     * @param type $criteria
     * @return type
     */
    public function getCategoriesData($criteria = array())
    {
        $qb = $this->createQueryBuilder('category')
            ->select('category.id, category.title, category.tag')
            ->where('category.deleted = 0');
        
        return $qb->getQuery()->getScalarResult();
    } 
}