# Admin modules routing configurations
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    
flickr:
    resource: "@FlickrBundle/Controller/"
    type:     annotation


# Route configs related to admin login page
admin_login:
    path:     /login/{isFront}
    defaults: { _controller: AppBundle:Security:login, isFront: false }
admin_login_check:
    path: /admin/login_check
admin_logout:
    path: /admin/logout