<?php

namespace FlikerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Get one or null categories
     * 
     * @param int $id
     * @return type
     */
    public function getCategory($id)
    {
        $qb = $this->createQueryBuilder('category')
            ->where('category.id = :id AND category.deleted = 0')
            ->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }    
    
    /**
     * Get all categories
     * 
     * @param bool $justQuery
     * @return type
     */
    public function getCategories($justQuery = true)
    {
        $qb = $this->createQueryBuilder('category')
            ->where('category.deleted = 0');
        
        if (!$justQuery) {
            return $qb->getQuery()->getResult();
        }
        
        return $qb->getQuery();
    } 
}